name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch (e.g., 'main' or 'master')

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter web
      run: flutter build web --dart-define=KEY=${{ secrets.KEY }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: build/web

