name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch (e.g., 'main' or 'master')

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '12'

    - name: Create .env File
      run: echo "KEY=${{ secrets.KEY }}" > .env

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
          flutter-version: '3.24.0'
          channel: 'stable'

    - name: verify flutter version
      run: flutter --version
  
    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter web
      run: flutter build web --dart-define=KEY=${{ secrets.KEY }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: build/web

