name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch (e.g., 'main' or 'master')

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '12'

    - name: Create .env File
      run: echo "KEY=${{ secrets.KEY }}" > .env

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true

    - name: verify flutter version
      run: flutter --version
  
    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter web
      run: flutter build web --release --dart-define=KEY=${{ secrets.KEY }} --base-href /pixabay_dummy/

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        if git remote | grep origin; then git remote set-url origin https://github.com/Mohitkoley/pixabay_dummy.git; else git remote add origin https://github.com/Mohitkoley/pixabay_dummy.git; fi

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: build/web
        allow_empty_commit: true
        force_orphan: true
    
    - name: Build APK and ios
      run:  flutter build apk --release --split-per-abi
    - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      
        #upload apk to artifacts with the name weather_app.apk with each iteration inceament the version code
    - name: Push to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*,build/ios/iphoneos/app.ipa"
        tag: v1.0.${{ github.run_number }}
        token: ${{ secrets.TOKEN }}
        body: |
            - Build ${{ github.run_number }}
            - Commit ${{ github.sha }}
            - Branch ${{ github.ref }}
            - Author ${{ github.actor }}```
        name: v1.0.${{ github.run_number }}
        prerelease: false
        draft: false
     
    # - name: Deploy to GitHub Pages
    #   uses: bluefireteam/flutter-gh-pages@v7
    #   with:
    #       webRenderer: canvaskit
    #       targetBranch: gh-pages
    #       baseHref: /pixabay_dummy/
    #       customArgs: --dart-define="KEY=${{ secrets.KEY }}"
          
      

